FROM php:8.3-fpm-alpine AS builder
RUN apk add --no-cache \
    postgresql-dev \
    oniguruma-dev \
    libxml2-dev && \
    docker-php-ext-install pdo pdo_pgsql mbstring xml

FROM php:8.3-fpm-alpine AS runtime
COPY --from=builder /usr/local/lib/php/extensions /usr/local/lib/php/extensions
COPY --from=builder /usr/local/etc/php/conf.d /usr/local/etc/php/conf.d
RUN apk add --no-cache libpq oniguruma libxml2 && \
    echo "clear_env = no" >> /usr/local/etc/php-fpm.d/www.conf
WORKDIR /var/www/admin
COPY public/ /var/www/admin/
EXPOSE 9000
CMD ["php-fpm"]
