FROM php:8.3-fpm-alpine

RUN apk add --no-cache \
    postgresql-dev \
    oniguruma-dev \
    libxml2-dev

RUN docker-php-ext-install \
    pdo \
    pdo_pgsql \
    mbstring \
    xml

RUN echo "clear_env = no" >> /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www/admin

COPY public/ /var/www/admin/

EXPOSE 9000

CMD ["php-fpm"]
